version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=db
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api/

  redis: 
    image: redis
    
  db:
    image: postgres:12.2
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  
  proxy:
    image: nginx:1.17.9
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      


