version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=db
    ports: 
      - 8080:8080
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports: 
      - 5000:5000

  redis: 
    image: redis
    
  db:
    image: postgres:12.2
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    


