version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
  redis: 
    image: redis

